name: "teamsPresenceBridge"
description: "this can be used as presence-sensor for MS-Teams"
version: "1.0.12"
url: "https://github.com/Dielee/teamsPresenceBridge"
slug: "teams-presence-bridge"
webui: "http://[HOST]:[PORT:5557]/"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  5557/tcp: 5557
options:
  azureApplicationId: ""
  azureClientKey: ""
  azureTenantId: ""
schema:
  azureApplicationId: str
  azureClientKey: str
  azureTenantId: str
